### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by garethrees** [mysociety/asknepal-theme#1]

**Comment by garethrees** [comment]
@Flupsy @paullenz has confirmed that we can pay for this.

**Comment by garethrees** [comment]
Let me know when its installed and I'll update the vhost config.

**Comment by Flupsy** [comment]
Certificate on order.

**Comment by Flupsy** [comment]
Certificate & key installed on server.

**Comment by garethrees** [comment]
Cheers :beers:. Done.
