### ISSUE TITLE
Start sending requests to authorities

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/asknepal-theme#15]
Email from Ravi:

'Could we now change setting on AskNepal -- the request email until now comes to ask nepal team -- could we now change it so it goes directly to authority and a copy of it comes to asknepal team too? Thank you for your help!'

**Comment by garethrees** [comment]
Can click follow on https://asknepal.info/list/all for an alert when a new request is made

**Comment by lizconlan** [comment]
waiting for response from Ravi before going ahead

**Comment by lizconlan** [comment]
Confirmation received, site redeployed
