### ISSUE TITLE
Supporter and Partners space

### ISSUE THREAD

**Issue by nikeshbalami** [mysociety/asknepal-theme#18]
As a project partner, I would like to have partners or supporter space where we can display the logo for partners.

**Comment by garethrees** [comment]
Hey @nikeshbalami. Did you have content for this that you'd like us to import?

**Comment by nikeshbalami** [comment]
I am working on it @garethrees , will let you know once it is done.

**Comment by nikeshbalami** [comment]
Hey @garethrees my colleagues, Pawan will be pushing some PR from now-onwards regularly. We are working some to improve portal UI, Hope you will manage some times to review those codes. Thanks in Advance :)
