### ISSUE TITLE
Contributors Page

### ISSUE THREAD

**Issue by nikeshbalami** [mysociety/asknepal-theme#19]
A separate space to thanks, development and translation contributors.

**Comment by garethrees** [comment]
Hey @nikeshbalami. Did you have content for this that you'd like us to import?

**Comment by nikeshbalami** [comment]
Woking on it, will let you know soon.

**Comment by nikeshbalami** [comment]
Hey @garethrees my colleagues, Pawan will be pushing some PR from now-onwards regularly. We are working some to improve portal UI, Hope you will manage some times to review those codes. Thanks in Advance :)

**Comment by garethrees** [comment]
No problem!

**Comment by nikeshbalami** [comment]
Hi @garethrees We are slowing sending Pull Request. Looking forward to you comment 👍

**Comment by ravinepal** [comment]
thanks, @nikeshbalami! 

hi @garethrees - grateful if your team could review these pull requests and merge them: https://github.com/mysociety/asknepal-theme/pulls
